# Generated by Django 5.1.7 on 2025-05-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_subject_remove_teacher_subject_teacher_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_img',
        ),
        migrations.AlterUniqueTogether(
            name='studentteacherrelation',
            unique_together={('student', 'teacher')},
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.RemoveField(
            model_name='studentteacherrelation',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
