# Generated by Django 5.1.7 on 2025-05-11 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_teacher_subjects_remove_profile_profile_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='status',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='status',
        ),
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
    ]
