# Generated by Django 5.1.7 on 2025-05-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_parent_status_remove_teacher_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
    ]
