# Generated by Django 5.1.6 on 2025-05-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_parent_gender_student_gender_teacher_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='student',
        ),
    ]
