# Generated by Django 5.1.7 on 2025-05-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_parent_student_remove_teacher_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
