# Generated by Django 5.1.6 on 2025-05-16 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_parent_student_remove_teacher_student'),
        ('quiz', '0005_userrank_quizsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_active', models.DateField(auto_now=True, null=True)),
                ('mastery_levels', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='userrank',
            options={'ordering': ['rank'], 'verbose_name': 'User Ranking', 'verbose_name_plural': 'User Rankings'},
        ),
        migrations.AddField(
            model_name='question',
            name='avg_time_spent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='discrimination_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_theme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='solution_explanation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='times_attempted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='times_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='times_incorrect',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='avg_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='avg_time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='completion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('Very Easy', 'Very Easy'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Very Hard', 'Very Hard')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='discrimination_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='question_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrank',
            name='accuracy_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrank',
            name='last_active',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userrank',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userrank',
            name='streak_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrank',
            name='topic_mastery',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userrank',
            name='weekly_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_file',
            field=models.FileField(blank=True, null=True, upload_to='quiz/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['user', 'quiz'], name='quiz_quizsu_user_id_c97088_idx'),
        ),
        migrations.AddIndex(
            model_name='userrank',
            index=models.Index(fields=['rank'], name='quiz_userra_rank_d7f53b_idx'),
        ),
        migrations.AddIndex(
            model_name='userrank',
            index=models.Index(fields=['total_score'], name='quiz_userra_total_s_612fed_idx'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
    ]
