# Generated by Django 5.1.7 on 2025-05-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_studentprogress_alter_quizsubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
