# Generated by Django 5.1.6 on 2025-05-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
